name = "swypt-landing"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[[workers.custom_domains]]
hostname = "swypt.app"

[[workers.custom_domains]]
hostname = "www.swypt.app"

[assets]
directory = "."
binding = "ASSETS"
